experience:
  data_path:
    description: The directory path to the folder containing the dataset.
    value: path/to/dataset/DATASETNAME.csv
  experiment_name:
    description: The name of the file to save the experimental results.
    value: TESTNAME
  metadata_path:
    value: path/to/dataset//METADATANAME.csv
  result_path:
    description: The directory path where the results will be saved.
    value: /path/to/results
pipeline:
  fs_methods:
    description: List of feature selection methods to use. You can choose two or more
      methods.
    valid_values:
    - f_statistic_selector
    - mutual_info_selector
    - random_forest_selector
    - svm_selector
    - xgboost_selector
    - rfe_rf_selector
    value:
    - f_statistic_selector
    - mutual_info_selector
    - random_forest_selector
    - svm_selector
    - xgboost_selector
  merging_strategy:
    description: The strategy for merging feature selection results. Choose only one
      merging strategy.
    valid_values:
    - union_of_intersections_merger
    - kemeny_young_merger
    - borda_merger
    value: union_of_intersections_merger
  num_repeats:
    description: The number of repeats (train/test folds) for the pipeline, it does also affect the test size 1/n_repeats of the dataset
    max_value: 10
    min_value: 2
    value: 5
  random_state:
    description: Seed used to fix feature selection method
    valid_values:
    - int
    - None
    value: 2024
  metrics:
    description: List of metrics to use for evaluation, need a list of exactly 3 metrics
    valid_values:
    - accuracy
    - f1_score
    - logloss
    - precision
    - recall
    - mae
    - mse
    - r2_score
    value:
    - f1_score
    - accuracy
    - logloss
  task:
    description: ML task, either regression or classification
    valid_values:
    - regression
    - classification
    value: classification
  num_features_to_select:
    description: Number of features to select, if None threshold is set to 10%
    valid_values:
    - int
    - None
    value: NUMBERS_OF_FEATURES
  n_jobs:
    description: to define number of cores for sklearn module
    valid_values:
    - postitive int or -1
    - None
    value: 1
preprocessing:
  categorical_columns:
  - NAME_OF_CATEGORICAL_COLUMN_1
  - NAME_OF_CATEGORICAL_COLUMN_2
  - NAME_OF_CATEGORICAL_COLUMN_TARGET
  columns_to_drop:
  - NAME_OF_COLUMN_TO_DROP_1
  - NAME_OF_COLUMN_TARGET
  drop_missing_values: true
  merge_key: NAME_OF_COLUMN_TO_MERGE
  normalize: true
  target_column: NAME_OF_COLUMN_TARGET
