name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[docs,build]"


    - name: Ensure root directory is included in PYTHONPATH
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        echo $PYTHONPATH

    - name: Build package
      run: |
        python -m build

    - name: Clean build directory
      run: |
        rm -rf docs/build/*

    - name: Build docs
      run: |
        export PYTHONPATH=$(pwd)
        echo "Building docs with PYTHONPATH: $PYTHONPATH"
        sphinx-build -b html docs/source docs/build/html -v

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html

    - name: Verify Imports
      run: |
        python -c "import ensemblefs.core.pareto; print('ensemblfs.core.pareto imported successfully')"
        python -c "import ensemblefs.feature_selection_pipeline; print('ensemblfs.feature_selection_pipeline imported successfully')"
