name: tests

on:
  push:
    branches:
      - main
      - '**'
  pull_request:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install project and test deps
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install -e .[test]

      - name: Verify imports
        run: |
          python -c "import moosefs, ensemblefs; print('import ok')"

      - name: Run pytest
        run: |
          pytest -q --maxfail=1 --disable-warnings

      - name: Upload junit/coverage (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-py${{ matrix.python-version }}
          path: |
            ./.pytest_cache/**
            ./coverage.xml
          if-no-files-found: ignore
          retention-days: 7

