name: tests

on:
  push:
    branches:
      - main
      - '**'
  pull_request:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create project venv
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install dev dependencies (editable)
        run: uv pip install -e . -e .[dev]

      - name: Verify imports
        run: uv run python -c "import moosefs; print('import ok')"

      - name: Ruff format check
        run: uv run ruff format --check .

      - name: Ruff lint
        run: uv run ruff check --output-format=github .

      - name: Run pytest
        run: uv run pytest -q --maxfail=1 --disable-warnings

      - name: Upload junit/coverage (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-py${{ matrix.python-version }}
          path: |
            ./.pytest_cache/**
            ./coverage.xml
          if-no-files-found: ignore
          retention-days: 7

      - name: Build package
        run: uv run python -m build

      - name: Verify distribution
        run: uv run twine check dist/*
